context:
  name: gifski
  version: "1.34.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: "https://github.com/ImageOptim/gifski/archive/${{ version }}.tar.gz"
  sha256: c9711473615cb20d7754e8296621cdd95cc068cb04b640f391cd71f8787b692c

build:
  number: 2
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - export LIBCLANG_PATH=$BUILD_PREFIX/lib/libclang${SHLIB_EXT}
      - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --features video --path  .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
    - libclang
    - clangdev
  host:
    - ffmpeg 5.*

tests:
  - script:
      - gifski --help

about:
  homepage: https://gif.ski/
  summary: "Highest-quality GIF encoder based on pngquant."
  description: |
    Highest-quality GIF encoder based on pngquant.
    gifski converts video frames to GIF animations using pngquant's fancy features for efficient cross-frame palettes and temporal dithering.
    It produces animated GIFs that use thousands of colors per frame.
    It's a CLI tool, but it can also be compiled as a C library for seamless use in other apps.
  license: AGPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/ImageOptim/gifski

extra:
  recipe-maintainers:
    - M-Sabrina
    - Hofer-Julian
